# Use the official Node.js runtime with Alpine as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json files first
COPY package.json .

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .


# Define the command to run the application
CMD ["npm","run", "start"]
